### ISSUE TITLE
Not loaded after HA upgrade to 2024.06.0

### ISSUE THREAD

**Issue by brusarp** [t3chguy/pinecil_ble#7]
After upgrading HA to 2024.06.0 an error appear 
![Screenshot_20240605_224222_Home Assistant.jpg](https://github.com/t3chguy/pinecil_ble/assets/14950532/79aad285-fa03-4e9e-a948-26111c9d6292)

**Comment by t3chguy** [comment]
Looks like the issue is that HA updated `bleak` and https://github.com/builder555/pinecil_lib/blob/master/pyproject.toml#L12C10-L12C17 is too strict

**Comment by t3chguy** [comment]
Opened https://github.com/builder555/pinecil_lib/issues/1

**Comment by brusarp** [comment]
> Opened [builder555/pinecil_lib#1](https://github.com/builder555/pinecil_lib/issues/1)

Good, thank you! 👍🏻

**Comment by t3chguy** [comment]
I will give the maintainer some time to respond, will consider forking if no solution is reached upstream.

**Comment by t3chguy** [comment]
The upstream maintainer has pushed and released a solution, will upgrade on this end

**Comment by t3chguy** [comment]
@brusarp I pushed a fix for the dependency version. It seems to work for me:

![image](https://github.com/t3chguy/pinecil_ble/assets/2403652/eaa63262-cc2a-43aa-9f4f-146f95139a4d)

let me know if it does for you

**Comment by brusarp** [comment]
Good, thank you!
The error is gone but I can't try to connect the soldering iron because I don't have it here with me right now...

**Comment by t3chguy** [comment]
ERR_NOT_ENOUGH_PINECILS

**Comment by brusarp** [comment]
Sorry for delay, I'm going to close this issue as I tested also with Pinecil and now all works. Thank you @t3chguy !
